### ISSUE TITLE
[Spike] Prepare multilingual setup

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-sample-app-react#199]
### Expected result

* Create a skeleton of [create-react-app](https://create-react-app.dev/) in typescript `npx create-react-app my-app --template typescript` (https://create-react-app.dev/docs/adding-a-router/) 
* [Add a router](https://create-react-app.dev/docs/adding-a-router)
* Try to set up and describe a simple showcase on how to handle multilingual similarly as it is for the current project but in the last router and by the latest best practices.

### Additional context

* Mind there are 2 sources of the data - Kontent and JSON
* We would like to preserve the different date/time format for different languages
* There are language prefixes showcased + URL slug for about-us/arcera-de (we might cut out one of these)
* Articles are identified by ID in the URL

**Comment by Chleba** [comment]
### Some points of interest about a multi-languages solution:

- hold language option in cookie or LocalStorage
- switch language with URL (anchor or part of URL (/{lang}/page)
- check default URL when language is not part of URL in 404-page view with the script that will get default language from LocalStorage or cookies then redirect to the right page
- static text will be stored in JSON files in a key-value storage object
- dynamic text from Kontent

**Comment by IvanKiral** [comment]
### Spike Result
The are created two versions for the spike project which uses two different libraries:
react-intl: https://github.com/IvanKiral/routing-react
react-i18n: https://github.com/IvanKiral/routing-react/tree/react-i18-next

We have decided to go with react-intl due to used workaround in react-i18n in multilangue routing.
The json files will have the flat format - means no nested objects (only key:value).
To use custom datetime formatting: https://formatjs.io/docs/react-intl/components/#formatteddateparts
It has the BSD-3-clause project must include:
 - The full text of the license
 - The original copyright notice

**Comment by Simply007** [comment]
Looks good! 

We need to think about a full copy of the license in #206
